### ISSUE TITLE
persistence issue

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#1125] opened 2019-03-01 15:23 UTC
```
app/log_exception : Exception on /scraper/work [POST]
Traceback (most recent call last):
  File "/app/recidiviz/ingest/scrape/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 237, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 182, in write
    database.write_people(session, people, metadata)
  File "/app/recidiviz/persistence/database/database.py", line 154, in write_people
    metadata)
  File "/app/recidiviz/persistence/database/database.py", line 190, in _save_record_trees
    session, root_people, metadata.last_seen_time)
  File "/app/recidiviz/persistence/database/update_historical_snapshots.py", line 60, in update_historical_snapshots
    context_registry.add_snapshot(snapshot)
  File "/app/recidiviz/persistence/database/update_historical_snapshots.py", line 359, in add_snapshot
    type=master_type_name, primary_key=master_entity_id))
ValueError: Snapshot already registered for master entity with type Charge and primary key 839058

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/scrape/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.scrape.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_ga_gwinnett' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {},
               'custom': {},
               'endpoint': 'http://www.gwinnettcountysheriff.com/smartwebclient/jail.aspx/AddMoreResults',
               'headers': None,
               'json': {'BeginBookDate': '',
                        'BeginReleaseDate': '',
                        'EndBookDate': '',
                        'EndReleaseDate': '',
                        'FirstName': '',
                        'IsDefault': False,
                        'LastName': '',
                        'MiddleName': '',
                        'RecordsLoaded': '1940',
                        'SortOption': 1,
                        'SortOrder': 1,
                        'TypeJailSearch': 0},
               'params': None,
               'post_data': None,
               'response_type': 'json',
               'task_type': 6},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-22T02:00:07.498796'}
```

**Comment by colincadams** [comment] 2019-03-01 15:24
https://pantheon.corp.google.com/logs/viewer?project=recidiviz-123&minLogLevel=0&expandAll=false&timestamp=2019-03-01T15:23:56.511000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-03-01T13:40:12.072Z&interval=PT1H&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20190228t175246&logName=projects%2Frecidiviz-123%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&scrollTimestamp=2019-03-01T15:23:47.754000000Z&dateRangeUnbound=forwardInTime

**Comment by zdg2102** [comment] 2019-03-01 20:17
Duplicate of #899

**Closed by zdg2102** 2019-03-01 20:17 UTC
