### ISSUE TITLE
Inferred release should run after a scrape session is completed.

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#405] opened 2018-12-26 16:51 UTC
Now it runs on a cron schedule no matter whether the scrape finished or not. This is suboptimal because a) we might wait longer than we have to to infer releases if the scrape finishes quickly and b) release is inferred even if the scraper did not complete ingestion, which causes false positives in the release logic.

**Comment by ohinds** [comment] 2019-02-12 20:15
This should be easy after #974

**Comment by arian487** [comment] 2019-03-06 18:40
Duplicate of https://github.com/Recidiviz/recidiviz-data/issues/1044

**Closed by arian487** 2019-03-06 18:40 UTC
Labels: enhancement, optimization
