### ISSUE TITLE
Add jurisdiction_id to all people

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#1153] opened 2019-03-01 20:25 UTC
This is so that we can join our data with the BJS data.

**Comment by rasmi** [comment] 2019-03-01 21:21
Duplicate of #368.

**Comment by zacharylawrence** [comment] 2019-03-02 16:25
@rasmi This bug and #368 seem unrelated? I think this might have been mistakenly closed.

**Comment by zacharylawrence** [comment] 2019-03-02 16:26
Ah, I think you meant #386!

**Closed by zacharylawrence** 2019-03-02 16:26 UTC

**Comment by rasmi** [comment] 2019-03-02 16:35
Yes sorry!
